export const questionAndAnswers = [
  {
    id: 1,
    answeredBy: "Aman",
    questionedBy: "Aman Sen",
    question: "What is the famous food of Agra?",
    answer: "Petha is the famous sweet of Agra",
    upvote: false,
    downvote: false,
    time: "22:45:00 PM",
    date: "1 Jan 2021",
  },
  {
    id: 2,
    answeredBy: "Nikhil",
    questionedBy: "Amartya",
    question: "What color is the sky?",
    answer:
      "The sky is of color blue.The color is blue because The Raman Effect",
    upvote: false,
    downvote: false,
    time: "16:20:00 PM",
    date: "10 July 2023",
  },
  {
    id: 3,
    answeredBy: "Nitish",
    questionedBy: "Abhishek",
    question: "When did the world war start?",
    answer: "The world war 1 started in 1914",
    upvote: false,
    downvote: false,
    time: "8:23:00 AM",
    date: "6 August 2021",
  },
  {
    id: 4,
    answeredBy: "Shubham",
    questionedBy: "Ankit",
    question: 'Which animal is known as the "Ship of the Desert"?',
    answer: "Camel",
    upvote: false,
    downvote: false,
    time: "23:22:00 PM",
    date: "3 May 2019",
  },
  {
    id: 5,
    answeredBy: "Abhishek",
    questionedBy: "Amartya",
    question: "How many consonants are there in the English alphabet?",
    answer: "21 Consonants",
    upvote: false,
    downvote: false,
    time: "11:55:04 AM",
    date: "22 June 2021",
  },
  {
    id: 6,
    answeredBy: "Amartya",
    questionedBy: "Nitish",
    question: "Who designed the National Flag of India?",
    answer: "Pingali Venkayya",
    upvote: false,
    downvote: false,
    time: "12:22:00 PM",
    date: "19 Dec 2022",
  },
];

export const questionLists = [
  {
    id: "1",
    questionedBy: "Kamal rastogi",
    question: "Which is the tallest mountain in the world?",
  },
  {
    id: "2",
    questionedBy: "Rahul Kumar",
    question: "Rainbow consist of how many colours?",
  },
  {
    id: "3",
    questionedBy: "Jatin Rawat",
    question: "Which is the largest plateau in the world?",
  },
  {
    id: "4",
    questionedBy: "Jatin Rawat",
    question: "Who designed the National Flag of India?",
  },
  {
    id: "5",
    questionedBy: "Rahul Kumar",
    question: "Difference between strees and strain?",
  },
  {
    id: "6",
    questionedBy: "Abhishek",
    question: "How many hours are there in a day?",
  },
  {
    id: "7",
    questionedBy: "Amartya",
    question: "What color is the sky?",
  },
  {
    id: "8",
    questionedBy: "Shubham",
    question: "How many days are there in a year?",
  },
  {
    id: "9",
    questionedBy: "Shivani",
    question:
      "How many vowels are there in the English alphabet and name them?",
  },
  {
    id: "10",
    questionedBy: "Astha",
    question: 'Which animal is known as the "Ship of the Desert"?',
  },
  {
    id: "11",
    questionedBy: "Shivani",
    question: "Which planet is known as the Red Planet?",
  },
  {
    id: "12",
    questionedBy: "Amartya",
    question: "When did the world war start?",
  },
  {
    id: "13",
    questionedBy: "Aman Sen",
    question: "What is the famous food of Agra?",
  },
];
